### ISSUE TITLE
Clojure tutorial

### ISSUE THREAD

**Issue by l3nz** [neomatrix369/awesome-graal#5]
Hi,
maybe you want to add my Clojure tutorial: https://www.astrecipes.net/blog/2018/07/20/cmd-line-apps-with-clojure-and-graalvm/ 
Thanks
l.

**Comment by neomatrix369** [comment]
That's awesome, you can create a PR by adding your tutorial to the correct section in https://github.com/neomatrix369/awesome-graal/blob/master/README.md

**Comment by l3nz** [comment]
I just did. Thanks!

**Comment by neomatrix369** [comment]
Fixed by #6
